<div class='instamojo'>
	<div class='errors'>
		<?php if(isset($errors)): ?>
			<?php $showPhoneBox = false; ?>
			<?php foreach($errors as $message): ?>
				<div class='alert alert-danger'><p style='color:red'><?= $message ?></p></div>
				<?php if(stristr($message,"phone") and !$showPhoneBox) $showPhoneBox = true;  ?>
			<?php endforeach; ?>
			<?php if($showPhoneBox): ?>
				<form method='post'>
					<label>Telephone</label><input type='text' name='telephone' value='<?php echo $telephone ?>' />
					<div><input type='submit' class='btn btn-primary' value='UPDATE TELEPHONE'></div>
				</form>
			<?php endif; ?>
		<?php else: ?>
			<div style="width:200px;margin:auto;margin-top:20px">
			<img style="width:100%" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."/Instamojo/spinner.gif"; ?>">
			<center>Redirecting you to Instamojo</center>
			</div>
			<form name='instapaymentredirect' action='<?= $url ?>'>
				<input type='hidden' name='embed' value='form'>
			</form>
			<script>
				document.instapaymentredirect.submit();
			</script>
		<?php endif; ?>
	</div>
	
</div>